apiVersion: v1
kind: Service
metadata:
  name: my-app-loadbalancer
spec:
  type: LoadBalancer
  selectors:
    app: calculator
  ports:
    - nodePort: 32000   
      port: 2000        # External LB port
      targetPort: 3000  # Pod container port
